// <auto-generated />
using Global.Access.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Global.Access.Migrations;

[DbContext(typeof(GlobalDbContext))]
[Migration("20260212000003_SeedMoreCities")]
partial class SeedMoreCities
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 128)
            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

        modelBuilder.Entity("Global.Manager.Entities.Country", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                .HasAnnotation("SqlServer:Identity", "1, 1");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("nvarchar(200)");

            b.HasKey("Id");

            b.ToTable("Countries", "dbo");

            b.HasData(
                new
                {
                    Id = 1,
                    Name = "Paraguay"
                },
                new
                {
                    Id = 2,
                    Name = "United States"
                },
                new
                {
                    Id = 3,
                    Name = "Chile"
                },
                new
                {
                    Id = 4,
                    Name = "Argentina"
                });
        });

        modelBuilder.Entity("Global.Manager.Entities.City", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                .HasAnnotation("SqlServer:Identity", "1, 1");

            b.Property<int>("CountryId")
                .HasColumnType("int");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("nvarchar(200)");

            b.HasKey("Id");

            b.HasIndex("CountryId");

            b.ToTable("Cities", "dbo");

            b.HasData(
                new
                {
                    Id = 1,
                    CountryId = 1,
                    Name = "Asuncion"
                },
                new
                {
                    Id = 2,
                    CountryId = 2,
                    Name = "Washington"
                },
                new
                {
                    Id = 3,
                    CountryId = 3,
                    Name = "Santiago"
                },
                new
                {
                    Id = 4,
                    CountryId = 4,
                    Name = "Buenos Aires"
                },
                new
                {
                    Id = 5,
                    CountryId = 1,
                    Name = "Encarnacion"
                },
                new
                {
                    Id = 6,
                    CountryId = 1,
                    Name = "Ciudad del Este"
                },
                new
                {
                    Id = 7,
                    CountryId = 2,
                    Name = "New York"
                },
                new
                {
                    Id = 8,
                    CountryId = 2,
                    Name = "Los Angeles"
                },
                new
                {
                    Id = 9,
                    CountryId = 3,
                    Name = "Valparaiso"
                },
                new
                {
                    Id = 10,
                    CountryId = 3,
                    Name = "Concepcion"
                },
                new
                {
                    Id = 11,
                    CountryId = 4,
                    Name = "Cordoba"
                },
                new
                {
                    Id = 12,
                    CountryId = 4,
                    Name = "Rosario"
                });
        });

        modelBuilder.Entity("Global.Manager.Entities.City", b =>
        {
            b.HasOne("Global.Manager.Entities.Country", "Country")
                .WithMany("Cities")
                .HasForeignKey("CountryId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Country");
        });

        modelBuilder.Entity("Global.Manager.Entities.Country", b =>
        {
            b.Navigation("Cities");
        });
    }
}
