// <auto-generated />
using Global.Access.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Global.Access.Migrations;

[DbContext(typeof(GlobalDbContext))]
[Migration("20260212000000_InitialCreate")]
partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 128)
            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

        modelBuilder.Entity("Global.Manager.Entities.Country", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                .HasAnnotation("SqlServer:Identity", "1, 1");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("nvarchar(200)");

            b.HasKey("Id");

            b.ToTable("Countries", "dbo");

            b.HasData(
                new
                {
                    Id = 1,
                    Name = "Paraguay"
                },
                new
                {
                    Id = 2,
                    Name = "United States"
                },
                new
                {
                    Id = 3,
                    Name = "Chile"
                },
                new
                {
                    Id = 4,
                    Name = "Argentina"
                });
        });
    }
}
